### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by bachorp**
In a single PR to avoid conflicts. If need be I can isolate individual patches.

Includes https://github.com/telekom/lazy-imports/pull/17 (this patch is not compatible with Python 3.7).

### CODE REVIEW

**Comment by bachorp** [comment]
@PhilipMay

**Comment by bachorp** [comment]
Hi @PhilipMay, no worries!
Note that I intend to submit additional patches after this one (in particular support for absolute imports).

**Comment by PhilipMay** [comment]
Hi @bachorp :

A colleague of mine was kind enough to review the PR and I'm going to merge it right away.

Unfortunately, there is no one on our side who has the time to actively maintain this project. Hence my question to you:

Do you want to take over the project? I could either move it to you or you could simply make a “friendly fork”. We would have to try it out.

What do you think?

**Comment by bachorp** [comment]
Thank you for the review and merge! I am happy to take over maintenance of the project. I guess that a transferal would be preferred over a fork as it preserves the Github history and external links but I am leaving this decision to you of course.

**Pull request merged**
